if event == 'BG' then
    PlaySound('Background')
elseif event == 'RollDice' then
    PlaySound('RollDice')
elseif event == 'true_pumpkin_king_Walk' then
	PlaySound('Walk')
elseif event == 'true_pumpkin_king_Run' then
	PlaySound('Run')
elseif event == 'true_pumpkin_king_Attack1' then
	PlaySound('Attack1')
elseif event == 'true_pumpkin_king_Attack2' then
	PlaySound('Attack2')
elseif event == 'true_pumpkin_king_Hurt01' then
	PlaySound('Hurt01')
elseif event == 'true_pumpkin_king_Hurt02' then
	PlaySound('Hurt02')
elseif event == 'true_pumpkin_king_Death' then
	PlaySound('Death')
elseif event == 'true_pumpkin_king_Pickup' then
	PlaySound('Pickup')
elseif event == 'true_pumpkin_king_Grab' then
	PlaySound('Grab')
end