if event == 'BG' then
    PlaySound('Background')
elseif event == 'RollDice' then
    PlaySound('RollDice')
elseif event == 'Walk' then
	PlaySound('Walk')
elseif event == 'Run' then
	PlaySound('Run')
elseif event == 'Attack1' then
	PlaySound('Attack1')
elseif event == 'Attack2' then
	PlaySound('Attack2')
elseif event == 'Hurt01' then
	PlaySound('Hurt01')
elseif event == 'Hurt02' then
	PlaySound('Hurt02')
elseif event == 'Death' then
	PlaySound('Death')
elseif event == 'Pickup' then
	PlaySound('Pickup')
elseif event == 'Grab' then
	PlaySound('Grab')
end